version: "3.8"

services:
  akdot_react:
    container_name: akdot_react_container
    build:
      context: ./react-ui
      dockerfile: Dockerfile
    image: akdot_react
    ports:
      - "80:3000"
  
  akdot_flask:
    build:
      context: ./flask-server
      dockerfile: Dockerfile
    container_name: akdot_flask_container
    image: akdot_flask
    restart: always
    ports:
      - "7001:7001"
    volumes:
      - ${HOST_BASE_PATH}/scenarioanalysis:${CONTAINER_BASE_PATH}/scenarioanalysis
      - ${HOST_BASE_PATH}/dashboard:${CONTAINER_BASE_PATH}/dashboard
      - ${HOST_BASE_PATH}/incidentsandmaintenance:${CONTAINER_BASE_PATH}/incidentsandmaintenance
      - ${HOST_BASE_PATH}/mainpage:${CONTAINER_BASE_PATH}/mainpage
  
